### ISSUE TITLE
error in finding 'extdata'

### ISSUE THREAD

**Issue by kc-li** [tsostarics/PitchMendR#83]
Hi, I would like to try out PitchMendR and followed the installation guide, but encountered an issue when trying to open the app. Could you suggest how to resolve this?

```
library(PitchMendR)
openEditor()
```
Then I get `Error in system.file("extdata", path, package = "PitchMendR", mustWork = TRUE) : no file found`

Thank you very much!

**Comment by tsostarics** [comment]
Hi, thanks for reporting. The problem should be fixed now-- the demo data was being ignored by R's package builder. Please reinstall in a new R session:

```r
# or devtools::install_github
remotes::install_github("tsostarics/PitchMendR", force = TRUE)

# this should return "demo_data.csv" and not ""
list.files(system.file("extdata", package = "PitchMendR"))
```

Let me know if this doesn't resolve the problem.

**Comment by kc-li** [comment]
This solves the problem, perfect! Many thanks!
